app:
  title: British Airways Developer Portal
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: http://localhost:7007
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: 5432
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: templates/kafka-topic/template.yaml
      rules:
        - allow: [Template]

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

scaffolder:
  defaultEnvironment:
    secrets:
      GITHUB_TOKEN: ${GITHUB_TOKEN}

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
